name: SmartContractor
options:
  bundleIdPrefix: cz.pteasima
  deploymentTarget:
    ios: "12.0"
targets:
  SmartContractorIos:
    type: application
    platform: iOS
    sources: [SmartContractorIos]
    dependencies:
      - target: SmartContractorFramework
    scheme:
      testTargets:
        - SmartContractorFrameworkTests
  SmartContractorFramework:
    type: framework
    platform: iOS
    settings:
      FRAMEWORK_SEARCH_PATHS: $inherited Frameworks
    dependencies:
      - framework: Frameworks/Prelude.framework
      - framework: Frameworks/Optics.framework
      - framework: Frameworks/Either.framework
    prebuildScripts:
      - path: scripts/R.sh
        name: R
    sources: [SmartContractorFramework]
    scheme:
      testTargets:
        - SmartContractorFrameworkTests
  SmartContractorFrameworkTests:
    type: bundle.unit-test
    sources: [SmartContractorFrameworkTests]
    platform: iOS
    
