name: SmartContractor
options:
  bundleIdPrefix: cz.pteasima
  deploymentTarget:
    ios: "12.0"
targets:
  SmartContractorIos:
    type: application
    platform: iOS
    sources: [SmartContractorIos]
    dependencies:
      - target: SmartContractorFramework
    scheme:
      testTargets:
        - SmartContractorFrameworkTests
  SmartContractorFramework:
    type: framework
    platform: iOS
    sources: [SmartContractorFramework]
    scheme:
      testTargets:
        - SmartContractorFrameworkTests
  SmartContractorFrameworkTests:
    type: bundle.unit-test
    sources: [SmartContractorFrameworkTests]
    platform: iOS
    
