name: SmartContractor
options:
  bundleIdPrefix: cz.pteasima
  deploymentTarget:
    ios: "12.0"
targets:
  SmartContractorFramework:
   type: framework
   platform: iOS
   sources: [SmartContractorFramework]
