//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
public struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap(Locale.init) ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)
  
  public static func validate() throws {
    try intern.validate()
  }
  
  /// This `R.color` struct is generated, and contains static references to 0 colors.
  public struct color {
    fileprivate init() {}
  }
  
  /// This `R.file` struct is generated, and contains static references to 0 files.
  public struct file {
    fileprivate init() {}
  }
  
  /// This `R.font` struct is generated, and contains static references to 0 fonts.
  public struct font {
    fileprivate init() {}
  }
  
  /// This `R.image` struct is generated, and contains static references to 0 images.
  public struct image {
    fileprivate init() {}
  }
  
  /// This `R.nib` struct is generated, and contains static references to 0 nibs.
  public struct nib {
    fileprivate init() {}
  }
  
  /// This `R.reuseIdentifier` struct is generated, and contains static references to 1 reuse identifiers.
  public struct reuseIdentifier {
    /// Reuse identifier `ContractCell`.
    public static let contractCell: Rswift.ReuseIdentifier<UIKit.UITableViewCell> = Rswift.ReuseIdentifier(identifier: "ContractCell")
    
    fileprivate init() {}
  }
  
  /// This `R.segue` struct is generated, and contains static references to 1 view controllers.
  public struct segue {
    /// This struct is generated for `ContractsViewController`, and contains static references to 1 segues.
    public struct contractsViewController {
      /// Segue identifier `HomeToContracts`.
      public static let homeToContracts: Rswift.StoryboardSegueIdentifier<UIKit.UIStoryboardSegue, ContractsViewController, UIKit.UITableViewController> = Rswift.StoryboardSegueIdentifier(identifier: "HomeToContracts")
      
      /// Optionally returns a typed version of segue `HomeToContracts`.
      /// Returns nil if either the segue identifier, the source, destination, or segue types don't match.
      /// For use inside `prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?)`.
      public static func homeToContracts(segue: UIKit.UIStoryboardSegue) -> Rswift.TypedStoryboardSegueInfo<UIKit.UIStoryboardSegue, ContractsViewController, UIKit.UITableViewController>? {
        return Rswift.TypedStoryboardSegueInfo(segueIdentifier: R.segue.contractsViewController.homeToContracts, segue: segue)
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  /// This `R.storyboard` struct is generated, and contains static references to 2 storyboards.
  public struct storyboard {
    /// Storyboard `Contracts`.
    public static let contracts = _R.storyboard.contracts()
    /// Storyboard `Support`.
    public static let support = _R.storyboard.support()
    
    /// `UIStoryboard(name: "Contracts", bundle: ...)`
    public static func contracts(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.contracts)
    }
    
    /// `UIStoryboard(name: "Support", bundle: ...)`
    public static func support(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.support)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.string` struct is generated, and contains static references to 0 localization tables.
  public struct string {
    fileprivate init() {}
  }
  
  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      try _R.validate()
    }
    
    fileprivate init() {}
  }
  
  fileprivate class Class {}
  
  fileprivate init() {}
}

public struct _R: Rswift.Validatable {
  public static func validate() throws {
    try storyboard.validate()
  }
  
  public struct nib {
    fileprivate init() {}
  }
  
  public struct storyboard: Rswift.Validatable {
    public static func validate() throws {
      try support.validate()
      try contracts.validate()
    }
    
    public struct contracts: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      public typealias InitialController = UIKit.UINavigationController
      
      public let bundle = R.hostingBundle
      public let contractsViewController = StoryboardViewControllerResource<ContractsViewController>(identifier: "ContractsViewController")
      public let druhej = StoryboardViewControllerResource<UIKit.UITableViewController>(identifier: "Druhej")
      public let name = "Contracts"
      
      public func contractsViewController(_: Void = ()) -> ContractsViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: contractsViewController)
      }
      
      public func druhej(_: Void = ()) -> UIKit.UITableViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: druhej)
      }
      
      public static func validate() throws {
        if _R.storyboard.contracts().druhej() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'druhej' could not be loaded from storyboard 'Contracts' as 'UIKit.UITableViewController'.") }
        if _R.storyboard.contracts().contractsViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'contractsViewController' could not be loaded from storyboard 'Contracts' as 'ContractsViewController'.") }
      }
      
      fileprivate init() {}
    }
    
    public struct support: Rswift.StoryboardResourceType, Rswift.Validatable {
      public let bundle = R.hostingBundle
      public let name = "Support"
      public let support = StoryboardViewControllerResource<SupportViewController>(identifier: "Support")
      
      public func support(_: Void = ()) -> SupportViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: support)
      }
      
      public static func validate() throws {
        if _R.storyboard.support().support() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'support' could not be loaded from storyboard 'Support' as 'SupportViewController'.") }
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate init() {}
}
